// global
export const CHANGE_GLOBAL_PROPS = 'CHANGE_GLOBAL_PROPS';

// NASA EPIC
export const CHANGE_NASA_EPIC_PROPS = 'CHANGE_NASA_EPIC_PROPS';
export const GET_NASA_EPIC_AVAILABLE_DATES = 'GET_NASA_EPIC_AVAILABLE_DATES';
export const GET_NASA_EPIC_IMAGES_DATA_BY_DATE =
  'GET_NASA_EPIC_IMAGES_DATA_BY_DATE';
